### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/jnigen#113]
- [x] Document all YAML config options in table
- [x] Briefly explain important concepts in README
- [x] INTERNALS.md or ARCHITECTURE.md for future contributors

**Comment by dcharkes** [comment]
I was just going to open an issue, you're quick! 🦊

**Comment by dcharkes** [comment]
Contents and order of topevel README.md (Inspired by ffigen again)

First, who are our audience in order of importance, and what do they need to know.

* First: prospective users
   * Is this package useful for me? What does this package give me? -> Start with immediate example.
* Second: users who want to try it out
   * How do I get the simplest example running?
* Third: users looking for reference documentation.
   * I want to achieve X, how do I do that?

Something along the lines of

=====================================================================================

Experimental bindings generator for Java bindings through `dart:ffi` and JNI.

### Example

* Prospective users of jnigen should be able to see the general idea. Example Java file, example jnigen.yaml and example Dart output and example C output. (Maybe we should consider Dart only bindings because that might be easier to understand.)
   a. This will also immediately explain which code is generated instead of explaining in English that code is generated.
   b. link to the examples folder with a single sentence, move the "(Re)generate ..." into the readme of the examples folder.

### Supported platforms
* the table and one sentence

### `packge:jnigen` and `package:jni`

`package:jnigen` generates C bindings which call Java methods through JNI, and Dart bindings which call these C wrappers through FFI. The generated code relies on common infrastructure provided by `package:jni` support library.

The repository contains these two packages.

* table with links to subfolders

### Using this package

* a la ffigen, with links to requirements

#### In Dart standalone

*  Note on Dart (standalone) target

### Installing dependencies

#### Dart tooling

#### C/C++ tooling

#### Java tooling

### Configuration

* yaml configuration table

**Comment by mahesh-hegde** [comment]
Shouldn't installation / requirements come before usage though?

**Comment by dcharkes** [comment]
> Shouldn't installation / requirements come before usage though?

I don't think so. First users write some code, then they run it and run into missing installation requirements.
And usage is kind of close to example as well. (The example shows the java code and config as inputs, and generated code as outputs. But the usage is the rest users have to write as text in files for it to work.)

**Comment by mahesh-hegde** [comment]
> I don't think so. First users write some code, then they run it and run into missing installation requirements.

I have seen many software / tool repos list installation & requirements first.

I will take some time to figure out an optimal order, if there's any :grin:

**Comment by dcharkes** [comment]
> > I don't think so. First users write some code, then they run it and run into missing installation requirements.
> 
> I have seen many software / tool repos list installation & requirements first.
> 
> I will take some time to figure out an optimal order, if there's any 😁

@mahesh-hegde I don't believe you've updated the PR yet. Would you mind switching it to draft until you do? (That signals to me you're not waiting on me to review it.)
