### ISSUE TITLE
Creating a new object array is too manual

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/jnigen#120]
Currently in the PR for array support (#118) it's too manual to create a new object array. For example, creating an array of strings with a length of 3 is done the following way:

```dart
JniArray<JniString> array = Jni.newArray<JniString>(
  3,
  Jni.findClass("java/lang/String"),
);
```

Couple of problems with this:

* Although the type is already given to be `JniString`, we still need to provide the function with `Jni.findClass`.
* The user has to know the Java signature (in this case `"java/lang/String"`) which is not ideal.

Ideally, we could have a syntax like this to create the array:

```dart
JniArray<JniString> array = Jni.newArray<JniString>(3);
```

This can work also for multidimensional arrays:

```dart
final twoDimArray = Jni.newArray<JniArray<JniString>>(3);
```

## A similar issue

We faced a similar issue with regards to the `operator []` for the arrays. Currently we generate an `extension` for each `JniArray<T>` since we couldn't do something like `T.fromRef` because `T` is a `Type`:

```dart
extension ${T}JniArray on JniArray<${T}> {
  ${T} operator [](int index) {
    return ${T}.fromRef(elementAt(index, JniType.objectType).object);
  }

  void operator []=(int index, ${T} value) {
    (this as JniArray<JniObject>)[index] = value;
  }
}
```

This includes one for array of arrays:
```dart
extension ArrayJniArray<T> on JniArray<JniArray<T>> {
  JniArray<T> operator [](int index) {
    return JniArray<T>.fromRef(elementAt(index, JniType.objectType).object);
  }

  void operator []=(int index, JniArray<T> value) {
    (this as JniArray<JniObject>)[index] = value;
  }
}
```

A similar approach could not be used here as we could have infinitely many multidimensional arrays.

@eernstg @lrhn Your feedback is appreciated!

**Comment by dcharkes** [comment]
We could solve these issues if we had dispatch on Types to static methods/getters/constructors.

If we would still like to support tree-shaking code AOT in a meaningful way, we would need to be able to specify that the type argument that we want to invoke static members from is const.

To be able to invoke static members from a type, we also would need to be able to specify somehow that static members on a super type must be provided in the sub type as well (which you currently do not have to). Which would unfortunately a big breaking change.

The typical workaround we have in multiple places for `dart:ffi`, is to transform the call sites in a transformer in the CFE.   For example https://api.dart.dev/stable/2.18.4/dart-ffi/StructPointer/ref.html:

```dart
extension StructPointer<T extends Struct> on Pointer<T> {
  external T get ref; // Call sites are transformed to a constructor call `T.#fromPointer(this)`.
}
```

Replacement logic pkg/vm/lib/transformations/ffi/use_sites.dart

```dart
  Expression _replaceGetRef(StaticInvocation node) {
    final dartType = node.arguments.types[0];
    final clazz = (dartType as InterfaceType).classNode;
    final constructor = clazz.constructors
        .firstWhere((c) => c.name == Name("#fromTypedDataBase"));
    // ...
    return ConstructorInvocation(constructor, Arguments([pointer]));
  }
```

We can _only_ do this because call-sites are forced to have a non-generic type argument.

We could consider extending this logic to also cover expressions in user code that refer to methods that are generated by `package:jnigen` instead of only expressions in user code that refer to methods in `dart:ffi`.

@mraleph you mentioned adding "private language features" for JNI interop earlier. Was something along the lines of this what you had in mind?

@eernstg @lrhn Rather than adding more special logic for interop (in this case Java interop), I'd prefer constructing an API from Dart language features. Having users repeat redundant information is really unergonomic. Maybe you have bright suggestions.

**Comment by HosseinYousefi** [comment]
One other solution that comes to mind is to parse `T.toString()` and construct the Java signature from that. We would need a map (yet again) of all the class names to their signatures, which could be a lot in case of Android SDK but at least we can still have tree shaking as it is `const Map<String, String> sig` with elements like `{"SomeClass": "com/example/SomeClass", ...}`.

Let's say `T.toString()` is `"JniArray<JniArray<SomeClass>>"` we can transform this to `"[[Lcom/example/SomeClass;"` using the map.

**Comment by mahesh-hegde** [comment]
> Let's say T.toString() is "JniArray<JniArray<SomeClass>>" we can transform this to "[[Lcom/example/SomeClass;" using the map.

This sounds like the best compromise possible.

We might consider having a generated static method `newArray()` on generated classes, but that will only help with one-dimensional arrays. (The use of 2 and 2+ dimension arrays in Java is really rare though).

---

The type-static method problem will again occur when in future someone wants to implement Java generics. For example `List<T extends JniObject>.get()` will have to return a `T`, but we can't call static constructor `fromRef` on a generic type T.

**Comment by mahesh-hegde** [comment]
> To be able to invoke static members from a type, we also would need to be able to specify somehow that static members on a super type must be provided in the sub type as well (which you currently do not have to). Which would unfortunately a big breaking change.

Thought experiment: introducing a keyword like `inherited` before a static method indicating it's inherited or overridden in a subtype.

But I don't know of a OOP language which lets you specify interfaces on types instead of objects.

(You can do something like this in C++, because C++ templates are loosely typed and also there's template specializations eg: implement a hash<T> for custom key type T. I am not aware of anything like that in Dart.)

**Comment by mraleph** [comment]
I think https://github.com/dart-lang/language/issues/356 is the closest language feature request to this. 

In the absence of direct language support I think we have to search for work-arounds, for which we can draw inspiration from other languages and possible implementation strategies for type classes / traits. 

For example instead of 

```dart
JniArray<JniString> array = Jni.newArray<JniString>(
  3,
  Jni.findClass("java/lang/String"),
);
```

we can write this: 

```dart
final /* JniArray<JniString> */ array = Jni.newArray(JniString.klass, 3);

class Jni {
  JniArray<T> newArray<T>(JniKlass<T> v, int length);
}

class JniString {
  JniKlass<JniString> get klass => ...;
}
``` 

Notice how `klass` carries type argument so you don't need to specify it twice.

For multi-dimensional arrays we could do: 

```dart
class JniKlass<T> {
  JniKlass<JniArray<T>> arrayKlass => ...;
}
```

so you can write: 

```dart
final /* JniArray<JniString> */ array = Jni.newArray(JniString.klass.arrayKlass, 3);
```

There might be slightly better names for this. 


> One other solution that comes to mind is to parse `T.toString()` and construct the Java signature from that.

I strongly discourage use of `T.toString()`. It's only [supposed to be used as a debugging aid](https://api.dart.dev/dev/2.19.0-372.0.dev/dart-core/Type/toString.html) and can change (e.g. release build can be returning some mangled string due to obfuscation).

**Comment by dcharkes** [comment]
> One other solution that comes to mind is to parse `T.toString()` and construct the Java signature from that.

* https://github.com/dart-lang/jnigen/issues/54

However, then we have no shaking for the contents of that const.

**Comment by lrhn** [comment]
I know very little about what's going on here, so let me try some questions instead of answers :)

With
```dart
JniArray<JniString> array = Jni.newArray<JniString>(
  3,
  Jni.findClass("java/lang/String"),
);
```
the problem you have is that you need to find the `java/lang/String` from the `JniString` type, right?

The `newArray` function generic, you can't really use the type argument for much except subtyping tests and as a type argument again (which is still better than what you can do with a `Type` object).

You have to support `JniArray<JniArray<JniString>>` too, I assume?

So you can't just have a map of all known types.
(Also if you generate new Jni-classes, those new types need to be registered in the map too, which is non-trivial since Dart does not have static initializers.)


Could you add a static method to every Jni type?

Then you'd do `JniString.newArray(3)`, and since `JniString` knows its own type representation, it can pass it one.
The generated function would just be:
```dart
  JniArray<JniString> newArray(int length) => Jni.newArray<JniString>(length, Jni.findClass("java/lang/String"));
```
That'll be a lot of methods to generate, but it will put the onus of knowing the class signature on the class it's a signature for.

Hmm. Probably still doesn't work, because `JniArray<JniString>` doesn't have a way to generate the class signature of itself, since it can't get the class signature of `JniString` from the type parameter, which makes `JniArray<JniString>.newArray` not work anyway.


Could you use *objects* to represent JniTypes instead of Dart types? (Or, more likely, in a addition to).

Then you could write
```dar
  JniArrayType(JniStringType()).newArray(4);
```
where
```
abstract class JniType<T extends Jni> {
  JniArray<T> newArray(int length);
  String get signature;
}
class JniArrayType<T extends Jni> implements JniType<JniArray<T>> {
  final JniType<T> elementType;
  JniArrayType(this.elementType);

  JniArray<JniArray<T>>(int length) => Jni.newArray(length, Jni.findClass(elementType.signature));
  String get signature => '[${elementType.signature}';
}
```
(Extend with more members as needed.)

That way you can carry around representations of the type with actual useful behavior, not just Dart types.

**Comment by HosseinYousefi** [comment]
> the problem you have is that you need to find the java/lang/String from the JniString type, right?

Right!

> Could you use objects to represent JniTypes instead of Dart types? (Or, more likely, in a addition to).

This is a similar approach to what @mraleph mentioned. We could do that.

**Comment by eernstg** [comment]
I'd need to make some guesstimations, too. Some basic properties first:

The set of classes in a Java program is not bounded, because there could always be more classes added by a classloader at run time. However, I'd expect that the Dart/Java interop system would be allowed to assume that this doesn't happen. So there would be a finite, statically known set of Java classes, each of which will have an associated id string (like `"java/lang/String"`).  An instance of such a class has no run-time representation of the actual type arguments.

In addition to that, Java has 8 or so primitive data types (byte, short, int, ...).

Finally, Java has arrays. There are 8 kinds of arrays of primitive data types, and one kind of reference type arrays, and that kind has a reified type argument.

What I see here is a finite, statically known set of run-time types, except that there is no limit on the nesting of reference type arrays. However, I'd be very surprised if it isn't enough to support, say, 5 levels of nesting, which means that we need to support `JniArray<T>`, ..., `JniArray<JniArray<JniArray<JniArray<JniArray<T>>>>>`, where `T` is a non-array type.

So we don't actually have to deal with a general situation like `OneType<AnotherType1<YetAnother>, .. AnotherTypeN>`, we just have a fixed set of types (for the given set of Java declarations).

Then how about using something like the following?:

```dart
// We'd like to write it like this, and get the inferred type `JniArray<JniString>`.
var array = Jni.newArray<JniString>(3);
```

I can't see from this thread where/how `Jni` is declared, but let's say that it's a class with a bunch of static methods.

```dart
const _arrayTypeIdPrefix = ['[', '[[', '[[[', '[[[[', '[[[[['];

String _addDepth(int depth, String s) => '${_arrayTypeIdPrefix[depth]}L$s';

const Map<Type, JniObject Function(int length, [int depth])> _dartTypeToArrayFactory = const {
  JniString: (length, depth) => _newArray(length, _addDepth(depth, 'java/lang/String'),
  JniBoolean: (length, depth) => _newArray(length, _addDepth(depth, 'java/lang/Boolean'),
  ...
};

class Jni {
  static JniArray<T> newArray<T extends JniObject>(int length) {
    var factory = _dartTypeToArrayFactory[T];
    if (factory != null) return factory(length, 1) as JniArray<T>;
    // error handling.
  }
  static JniArray<JniArray<T>> newArray2<T extends JniObject>(int length) {
    var factory = _dartTypeToArrayFactory[T];
    if (factory != null) return factory(length, 2) as JniArray<JniArray<T>>;
    // error handling.
  }
  ...
  static JniArray<JniArray<JniArray<JniArray<JniArray<T>>>>>
      newArray5<T extends JniObject>(int length) {
    var factory = _dartTypeToArrayFactory[T];
    if (factory != null) {
      return factory(length, 5) as JniArray<JniArray<JniArray<JniArray<JniArray<T>>>>>;
    }
    // error handling.
  }
}
```

I'm sure it's wrong in various ways, but the idea is that we rely on the simplicity of the run-time type universe: All types are non-generic except arrays, and each nested array type is fully determined by its depth and innermost element type. The `_newArray` function is a low-level feature (I'm guessing that something like that can be expressed rather easily, as a variant of the `newArray` described in the text of this issue).

(There is an esoteric exception to the rule that instances of generic Java classes don't reify their type arguments: instances of anonymous classes have the value of the type argument baked in, similarly to `class FooInt extends Foo<int> {}`, where `int` is baked into `FooInt`. I don't know if that breaks everything.)

**Comment by eernstg** [comment]
> I don't believe this to be true. We will likely start mapping Java classes
> type arguments to Dart classes with type arguments. For example 
> `MyFoo<ArrayList<JniArray<ArrayList<JniArray<MyBar>>>>>`.

I was referring to _run-time_ types, because that's the level of specificity which is required in order to create a specific Java object. So if `MyFoo` is a generic Java class taking one type argument (`public class MyFoo<X extends SomeType> ...`) and you wish to create a `MyFoo<ArrayList<JniArray<ArrayList<JniArray<MyBar>>>>>`, then there is no need to communicate `ArrayList<JniArray<ArrayList<JniArray<MyBar>>>>` to the JVM, you just need to ask for a new instance of `MyFoo`.

In Dart code you may well want to use types with type arguments in order to help the Dart developer keep track of the intended type arguments, but I don't see a need to introduce a lot of complexity in the low-level APIs that are actually used to create instances of Java classes.

However, Java arrays _do_ have reified type arguments, and we have those 8 kinds of primitive arrays as well (nested to some level, e.g., `MyFoo[]` or `int[][]`). So we must provide a sufficient amount of information to the JVM, such that it can create an array with the correct reified type argument.

At this point it is crucial that the set of non-array run-time types is finite: We just need to be able to create an array of any given non-array run-time type, nested a certain number of levels. So we could ask for a 1-dimensional array of `MyFoo`, or a two-dimensional array of `int`, etc., but the list has a finite length _k_, and if we are ready to restrict array nesting to a fixed number of levels _a_ then we only need the ability to create _a * k_ different types of JVM objects.

> We don't have reified generics in Java, we might not reify them at runtime
> for the Dart objects based on the runtime type,
> but at least we could reify the type arguments with the compile-time types.

Actually, it would be great if the Dart representation of the type of any given JVM object were invariant, because the JVM object, if not an array, has no way to protect itself from soundness violations in the JVM heap. So it would be really nice if the Dart program could avoid providing a specific JVM object of type `MyFoo<T>` to a piece of Java code that expects a `MyFoo<S>` where `T != S`, and this kind of protection of the JVM heap would be even more powerful if the type arguments are reified on the Dart side.

Of course, it is very much possible that the Dart side doesn't have enough information to be able to do this (say, if the Java code returns a `MyFoo<T>` with static type `java.lang.Object`). But if we can do something in this area it might be very helpful in relation to JVM soundness.

**Comment by dcharkes** [comment]
> Actually, it would be great if the Dart representation of the type of any given JVM object were invariant (so they would jump start the use of the possibly upcoming feature https://github.com/dart-lang/language/issues/524)

Since this is a package, we should easily be able to change the generator to do that and bump the major version. We'd be happy to be first adopters of such a new language feature! 🎉

**Comment by dcharkes** [comment]
I like passing in an object that can construct the Java signature string.

However, I'd prefer centering the API as much as possible around a single Dart class/type per Java class/type:

* Having a JNI reference to it should be an object of that class
* Interacting with that reference (calling methods, reading fields) should be on an object of that class
* Creating a new instance should be a (named) constructor on that class
* Having arrays or generics with these as type arguments, should have that type in the Dart reified type arguments and Dart static analysis

But, we need a non-JNI-reference object to be able to call the getJavaSignatureString on, and for that we need a separate class.

I like @mraleph's solution most:

* That class you interact with all the time has a `.klass` getter which returns an object that has to be passed in to our array instantiation.

When putting generics in the mix, the API would then look something like:

Constructing a `JniArray<JniArray<Mybar<MyKey, MyValue>>>`:

```dart
final array1 = JniArray.newInstance(
  JniArray.klass(
    MyBar.klass(MyKey.klass, MyValue.klass),
  ),
  3,
);
// and equivalently:
final array2 = JniArray.klass.newArray(
  MyBar.klass(MyKey.klass, MyValue.klass),
  3,
);

```

(More details: https://github.com/dart-lang/jnigen/issues/123#issuecomment-1306015360)

(Not sure if it should be `.klass` or `.type`.)

One issue with this approach is that the primitives are typedefs instead of proper types (stemming from the fact that this is how `jni.h` defines them.) I'd like to be able to have:

```dart
// typedef JBoolean = ffi.Uint8;
extension JBooleanExt on JBoolean {
  static JniBooleanTypeClass klass = JniBooleanTypeClass();
  // or
  static JniBooleanTypeClass get klass => JniBooleanTypeClass();
}

void main(){
  final array = JBoolean.klass.newArray(3);
  // and not:
  final array = JniBooleanTypeClass().newArray(3);
}
```

That would put less emphasis on `JniBooleanTypeClass` and more on `JByte`

**Comment by HosseinYousefi** [comment]
Closing, fixed as of https://github.com/dart-lang/jnigen/commit/25eb870db47acf2a1a0c35e22ded5ecaf9cd1e95#.

Thanks to @dcharkes, @mraleph, @lrhn, and @eernstg for the ideas.
