### ISSUE TITLE
`package:jni` support multiple JVMs

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/jnigen#121]
It currently assumes a single JVM.

This makes a _lot_ of sense from the Flutter Android perspective, as we _only_ have a single JVM there.

However, on desktop one could have more than one JVM.

* One example would be loading multiple packages that all use `package:jni` under the hood, but that are not aware of each other.
* Another example is loading multiple scripts concurrently into separate isolates, or interleaving them with async, such as our own tests do.
  * https://github.com/dart-lang/jnigen/issues/44
  * https://github.com/dart-lang/jnigen/issues/51

Could we come up with an API and implementation design that is nice for when there's a single JVM (Flutter Android is our most important use case), but that would still work with multiple JVMs on desktop?

cc @mahesh-hegde @HosseinYousefi

**Comment by mahesh-hegde** [comment]
> One example would be loading multiple packages that all use package:jni under the hood, but that are not aware of each other.

It already works with single JVM because all are initialized using `Jni.initGeneratedCodeLibrary` which passes required pointers to loaded DLL.

> Another example is loading multiple scripts concurrently into separate isolates, or interleaving them with async, such as our own tests do.

This is a valid use case.

#44 is very likely a timing issue in the order of calling `Spawn in C code` from different scripts. We might use some locking there.

If a spawn is already completed before second spawn, `JvmExistsException` is thrown.

In general we can use some locking primitive in few places where isolates can conflict in VM loading, class loading etc..

**Comment by mahesh-hegde** [comment]
A multi-JVM design will be pretty unergonomic.

Currently we have `JniObject` etc, and map class-to-class in order to get the same usage as java classes.

With separate JVMs, we should to pass JVM as a parameter (at least in all entry points, like static methods & ctors.).

One JVM per isolate maybe implementable, but my opinion it's better if all `spawns` from different caller isolates synchronize on a mutex.

**Comment by dcharkes** [comment]
> One JVM per isolate maybe implementable, but my opinion it's better if all spawns from different caller isolates synchronize on a mutex.

We should at least implement that so we can get rid of the `-j1` locally and on the CI.

Also, we should rename `Jni.spawn` to `Jni.singleton` or something.

**Comment by dcharkes** [comment]
One idea sparked by @HosseinYousefi's comments earlier:

We can generate an optional named argument `context` to everything that could be done on different JVMs.

* Context argument: Calling a constructor.
* No context argument: Calling a method on an object, it has to be on the JVM the method is on.

(Of course this only solves part of the API issue, not the implementation issues.)
