### ISSUE TITLE
[Docs] Please document the differences between, and when to use JNI, over `MethodChannel`s

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/jnigen#201]
hello,

Im a flutter beginner, and currently working with flutter's `MethodChannel`s, to communicate with respective platforms, but found it quite un-reliable. I read about JNI sometime ago,

But I:
- Neither know where to start, and 
- Should I even consider JNI, also 
- In which all situations, JNI should be preferred over `MethodChannel`s,

I found [this](https://stackoverflow.com/questions/74222966/how-flutter-methodchannel-works-and-how-it-is-different-from-interop), helpful, but not much,

thanks

**Comment by mahesh-hegde** [comment]
Hi,

Part of the problem is `jnigen` is still WIP (as you can see the version number), and we are yet figuring out how to do few things properly with limited interface exposed by JVM and quirks of the android build system.

For example you can't do callbacks into Dart code from Java, and we aren't sure about how to approach this. (We have discussed briefly about 3 possible techniques in past threads).

> Should I even consider JNI

The advantage is you can bind existing libraries, and it's fairly straightforward exposing the same interface as the library itself. In contrast, I think even using `Pigeon` with method channel requires you to write your own platform side code implementing the expected interface (correct me if I am wrong).

You can also bind your own Java code. As long as the library or classes against which you generated bindings is in `classpath` (I.e bundled with app using appropriate proguard rules), generated code works.

For more information I'd encourage you to look into the `jnigen/example` folder. I think they are good enough to get you started. Also look at respective READMEs in examples.

If you find integrating C library painful, you can use single_file and dart_only features to get single `.dart` file like ffigen.

**Comment by gintominto5329** [comment]
Thanking you for giving your time, and helping me out.

May i ask, in how much time, you **expect** JNI, to be properly working and stable, on android, like a month, a quarter, or dart-3 stable?

thanks,

**Comment by HosseinYousefi** [comment]
> May i ask, in how much time, you **expect** JNI, to be properly working and stable, on android, like a month, a quarter, or dart-3 stable?

It's tough to say when it's going to be fully stable. However, I encourage you to experiment with the package and raise issues when you encounter them.
