### ISSUE TITLE
Nested static class not found

### ISSUE THREAD

**Issue by AnisovAleksey** [dart-lang/jnigen#287]
Jnigen doesn't generate code for nested static class like `Builder` in following example
```
public class Config {
    public static Builder newConfigBuilder(@NonNull String var0) {
        return new Builder(var0);
    }


    public static class Builder {
        @NonNull
         private final String a;

         protected Builder(@NonNull String var1) {
            this.a = var1;
        }
    }
}
```

in **jnigen.yaml**
```
classes:
  - 'com.example.Config'
  - 'com.example.Config.Builder'
```

and I got error:
`Not found: [com.example.Config.Builder]`

**Comment by HosseinYousefi** [comment]
> Not found: [com.example.Config.Builder]

That's because the identifier for a nested class uses a dollar sign `$`:

`com.example.Config$Builder`

**Comment by mahesh-hegde** [comment]
That's one corner case I missed in summarizer.

In source, `com.example.Config` should pull in `Config$Builder` too. In ASM (compiled JAR), you have specify `Config$Builder` as well. (This is because we are searching matching files not "classes" per se).

Ideally it should do the same in later case too.

**Comment by HosseinYousefi** [comment]
I believe this has answered your question. Closing.
