### ISSUE TITLE
Support parsing directly from Kotlin sources

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/jnigen#292]
This is useful to get javadocs and argument names from the `xyz-sources.jar` when the source itself is written in Kotlin instead of Java.

**Comment by mahesh-hegde** [comment]
Would be difficult to find a documented parser for kotlin.

Few considerations.

* you would probably want to use official parser, because new syntax and features will be added and you have to keep up.

* Official parser may not have a stable API

Another way to do it is use the JAR / class file to get the API structure, and use an approximate parser [^fn1], which extracts doc comments and associates them with symbols in JAR.
    * Some sort of debug info mechanism?

_Or even more crazy idea: parse the javadoc JAR instead of source JAR, with an HTML parser._

[^fn1]: whats the state of art here? Treesitter? ANTLR? YACC or some other national geographic LR parser generator?

**Comment by HosseinYousefi** [comment]
Argument names for Kotlin actually exist in the metadata. So there is no need to even have access to sources! So #300 will solve this issue. JavaDocs/KDocs will remain though.

**Comment by mahesh-hegde** [comment]
Check this out. cant tell when stuff get deprecated, though.

https://kotlinlang.org/docs/dokka-plugins.html

Or crazy idea I know, output to Javadoc and parse the Javadoc HTML. (If I am not wrong, intellij also does parse javadoc.)

**Comment by HosseinYousefi** [comment]
Yes, that's not so crazy. Especially since we get most of the information we need from the metadata anyways and only javadocs remain.

**Comment by HosseinYousefi** [comment]
We should **definitely** parse the bytecode to use JNI anyways. It doesn't make that much sense to support parsing directly from Kotlin other than for the documentation. Tracking that separately in #316, and closing this as not planned.
