### ISSUE TITLE
`ensureNotDeleted` not called in the generated bindings

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/jnigen#359]
We're not calling `ensureNotDeleted` to throw `UseAfterFree`.

One idea to make sure any method call will have checked for this, is to change `JReference`'s `final reference` into the pair of `final _reference` and `Pointer<Void> get reference { ensureNotDeleted(); return _reference; }`

@mahesh-hegde @dcharkes Would this cause too many unnecessary checks?

**Comment by dcharkes** [comment]
From an encapsulation point of view, that would be a nicer solution indeed. (With the only caveat that you shouldn't hang on to that reference in a var in a long block of code where you might delete in between multiple uses: so that should go in the doc comment on the getter.)

I wouldn't worry about performance. most likely the small method will get inlined and it's just a bool check.
