### ISSUE TITLE
Issue: Not able to generate bindings for Gradle hosted library

### ISSUE THREAD

**Issue by yardexx** [dart-lang/jnigen#405]
Hello!

I am trying to implement jnigen to fork of Flutter plugin. Plugin is using Gradle dependency which has classes (library API) from which I want to generate bindings. However, I am unsuccessful and jnigen is throwing exception:
<img width="953" alt="image" src="https://github.com/dart-lang/jnigen/assets/62177414/12ae02a2-e8d1-49b8-99c2-aa23db0a2244">

I am following your pdfbox example, as well as kotlin plugin example.

**Steps to replicate**
1. Clone [repository, branch experimental/ffi](https://github.com/yardexx/freerasp/tree/experimental/ffi)
2. Run dart run jnigen --config jnigen.yaml in library root

Maybe it's something I'm doing wrong? 

Thanks for help.

**Comment by yardexx** [comment]
Issue resolved.

Found out that there is `add_gradle_sources` (undocumented) under android_sdk_config section. However, this solution seems to be not bulletproof since dependencies are retrieved from application build.gradle - I have to add Gradle dependency for Java library in build.gradle of **example** in order to be able to generate bindings.

It's bit odd - plugins add dependencies in build.gradle under `android` folder (on package level), however, jni doesn't seem to see them there.

**Comment by HosseinYousefi** [comment]
Yes, this is indeed an odd behavior. In general gradle support can be improved, it now uses the place where gradle caches the libraries after running some command like`flutter build apk`. This command cannot be run for a project without a `main` function – that's why currently you need to use `example` and yes, it doesn't find the "nested" dependencies in the cache either, so you'd have to add the same gradle dependencies again in `example`.

You can see this here in `package:cronet_http` as well: https://github.com/dart-lang/http/blob/master/pkgs/cronet_http/example/android/app/build.gradle#L70-L72

Related open issues:
* https://github.com/dart-lang/jnigen/issues/33
* https://github.com/dart-lang/jnigen/issues/293
