### ISSUE TITLE
Generics support

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/jnigen#66]
We should investigate mapping Java generics to Dart generics.

Please note that Java generics are erased before runtime, but Dart generics are not. This gives us two options:

* Always instantiate the Dart generic with the static generic.
* Always instantiate the Dart generic with `Never`.

A prime use case to support would be `ArrayList` in which the generic is used for the getters and setters as well.

**Comment by mahesh-hegde** [comment]
Consider a use case of mapping a generic collection type `List<T>` in Java

class List<T extends JniObject> extends Collection<T> {
    get<T>() => // how do we call T.fromRef() here, for generic T extends JniObject?
}

Since all java objects are untyped void pointers after this layer, I think the main advantage we expect from generics support is type safety. Otherwise it's always possible to map every method to it's erased parameter and return types, i.e the most specific possible superclass.
