### ISSUE TITLE
'\r\n' vs '\n' on windows.

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/jnigen#78]
It seems `writeln` writes platform-specific line endings. But in jnigen bindings I have liberally used `\n` in binding strings.

The recommended git configuration converts `\r\n` to `\n` on checking in, so it hasn't been a problem so far.

But are there use cases where it matters? Whats a good choice here?

@dcharkes @liamappelbe

**Comment by liamappelbe** [comment]
I don't think it matters. The only time I've seen it come up is in ffigen's integration tests. We remove all the '\r' from the generated output before comparing it to the expected result, so that the tests work on windows.

As for '\n' in string literals, I'm pretty sure that those are also translated to '\r\n' on windows.

**Comment by mahesh-hegde** [comment]
Thanks!
