### ISSUE TITLE
jni:setup should generate bindings for all native dependencies.

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/jnigen#91]
Now `jni:setup` builds `package:jni`'s DLL, since the other packages are structured the same way w.r.t native bindings, we are using same script with `-p` flag to specify another package.

`dart run jni:setup && dart run jni:setup -p pdfbox_plugin`

However, this is not neat.

I think by default, `setup` should go through dependency list, and build the packages with `ffiPlugin` specified in pubspec. We can always provide it custom folders or package names through CLI, but default should be imitating what flutter's bundling does.

Also, should this script be in `jnigen` instead of `jni`?

**Comment by dcharkes** [comment]
> I think by default, `setup` should go through dependency list, and build the packages with `ffiPlugin` specified in pubspec. We can always provide it custom folders or package names through CLI, but default should be imitating what flutter's bundling does.

I think relying on `ffiPlugin` is fragile because it doesn't enable Dart standalone. Also, it could be something else than jnigen generated code when it is an `ffiPlugin`.
`src/MakeFile.txt` is also fragile, because it could be something else than jnigen. And jnigen could be configured to use a different path than `src/MakeFile.txt`

That being said, having something automatic would be nice indeed.

How about we add a "Generated by package:jnigen." comment to the `src/CMakeLists.txt` and check both for that file _and_ a comment in that file? That way we don't accidentally build something that we didn't generate.

If devs output to a different path, I don't really know how to solve that, yet.

> Also, should this script be in `jnigen` instead of `jni`?

I think that makes sense indeed. jnigen is our main name. jni is the helper lib.

**Comment by dcharkes** [comment]
> If devs output to a different path, I don't really know how to solve that, yet.

I have been working on standardizing `bin/setup.dart` or `bin/native.dart` as a CLI for native builds in general. And then `dart run` and `dart compile` (and even `flutter build`) would invoke that standardized CLI for all dependencies that have it. When that infrastructure is ready, we could make jnigen generate a `bin/native.dart` that has a single line invocation of the `src/CMakeLists.txt` (when can then actually generate the right path and find it if it was in a different output path), and the jnigen:setup step wouldn't have to do the packagesConfig traversal anymore because `dart` and `flutter` would do that.

For now, because I haven't standardized this CLI yet, I think your proposed solution is a good one and we should land it.

**Comment by mahesh-hegde** [comment]
Few questions before I implement it.

1. Comment format

Is `## jnigen_native_build` sufficient as a comment directive for building?

2. Script location

`jnigen:native_build`? or `jnigen:build_native`? Any other suggestions?

**Comment by mahesh-hegde** [comment]
> If devs output to a different path, I don't really know how to solve that, yet.

I have an `-s` option in current PR which would only build the source directory specified instead of automatically traversing packageConfig. THat should be sufficient for now.

On Android, they can always add an externalNativeBuild to gradle.

**Comment by mahesh-hegde** [comment]
> I think that makes sense indeed. jnigen is our main name. jni is the helper lib.

But on the other hand this will require client packages of a generated library to depend on `jnigen`.

I have pushed the comments change, but thinking of holding back this one.

**Comment by dcharkes** [comment]
> > I think that makes sense indeed. jnigen is our main name. jni is the helper lib.
> 
> But on the other hand this will require client packages of a generated library to depend on `jnigen`.

Good point. Then `dart run jni:setup` is better indeed, because people will already transitively depend on `package:jni`.
